### ISSUE TITLE
Get to a working state

### ISSUE THREAD

**Issue by Phalanxia** [Phalanxia/Maid-IRC#30]

**Comment by Phalanxia** [comment]
Added enhancement label because it made me giggle.

**Comment by alureon** [comment]
Phalanxia opened this issue 
9 months ago

**Comment by Phalanxia** [comment]
I stopped working on it for like 5-6 months :p

**Comment by gdude2002** [comment]
HIGH PRIORITY ENHANCEMENT 

I feel like this has been in an ad somewhere.. 

Good to see you're back to working on this \o/
